/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'u-',
  separator: ':',
  important: false,
  content: [
    './app/components/**/*.vue',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/composables/**/*.{js,ts}',
    './app/app.vue',
  ],
  theme: {
    screens: {
      sm: '600px',
      md: '900px',
      lg: '1200px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: 'var(--white)',
      black: 'var(--black)',
      // Primary — ocean blue (A Coruña / Atlantic)
      blue: {
        lightest: 'var(--blue-lightest)',
        lighter: 'var(--blue-lighter)',
        light: 'var(--blue-light)',
        DEFAULT: 'var(--blue)',
        dark: 'var(--blue-dark)',
        darkest: 'var(--blue-darkest)',
      },
      // Accent — warm sand/gold
      sand: {
        light: 'var(--sand-light)',
        DEFAULT: 'var(--sand)',
        dark: 'var(--sand-dark)',
      },
      // Semantic
      green: {
        light: 'var(--green-light)',
        DEFAULT: 'var(--green)',
        dark: 'var(--green-dark)',
      },
      red: {
        light: 'var(--red-light)',
        DEFAULT: 'var(--red)',
        dark: 'var(--red-dark)',
      },
      // Gray scale
      gris: {
        2: 'var(--gris-2)',
        5: 'var(--gris-5)',
        7: 'var(--gris-7)',
        10: 'var(--gris-10)',
        15: 'var(--gris-15)',
        20: 'var(--gris-20)',
        30: 'var(--gris-30)',
        40: 'var(--gris-40)',
        50: 'var(--gris-50)',
        60: 'var(--gris-60)',
        70: 'var(--gris-70)',
        80: 'var(--gris-80)',
        90: 'var(--gris-90)',
      },
    },
    spacing: {
      0: '0',
      px: '1px',
      2: '2px',
      4: '4px',
      6: '6px',
      8: '8px',
      10: '10px',
      12: '12px',
      14: '14px',
      16: '16px',
      18: '18px',
      20: '20px',
      24: '24px',
      28: '28px',
      32: '32px',
      36: '36px',
      40: '40px',
      48: '48px',
      56: '56px',
      64: '64px',
      72: '72px',
      80: '80px',
      96: '96px',
      // Semantic spacing (from CSS custom properties)
      sixteenth: 'var(--spacing-sixteenth)',
      eighth: 'var(--spacing-eighth)',
      quarter: 'var(--spacing-quarter)',
      half: 'var(--spacing-half)',
      base: 'var(--spacing-base)',
      second: 'var(--spacing-second)',
      third: 'var(--spacing-third)',
      fourth: 'var(--spacing-fourth)',
      fifth: 'var(--spacing-fifth)',
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      serif: 'var(--font-serif)',
      display: 'var(--font-display)',
      mono: 'var(--font-mono)',
    },
    fontSize: {
      '2xs': 'var(--font-size-2xs)',
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      md: 'var(--font-size-md)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-5xl)',
    },
    extend: {
      maxWidth: {
        'container-medium': 'var(--max-w-container-medium)',
        'container-large': 'var(--max-w-container-large)',
        'container-x-large': 'var(--max-w-container-x-large)',
      },
      lineHeight: {
        tight: '1.2',
        normal: '1.5',
        relaxed: '1.618',
      },
    },
  },
  plugins: [],
}
